title: SF Space
description: My personal website
show_downloads: true
google_analytics: UA-88784993-1
twitter_username: Sam_Farrens
title_image: /assets/images/homeimage.png
post_author: Samuel Farrens
image_path: /assets/images
url: "https://sfarrens.github.io"

plugins:
  - jekyll-target-blank

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
   toc_levels: 1..2

exclude: [vendor]
