# config:
site_name: 'SF Space'
site_author: 'Samuel Farrens'
copyright: 'Copyright (c) 2016 Samuel Farrens'

docs_dir: 'docs'
theme: 'mkdocs'

extra:
  logo: 'images/mythosaur.jpg'
  author:
    github: 'sfarrens'
    twitter: 'Sam_Farrens'
  palette:
    primary: 'red'
    accent: 'blue'
  font:
    text: 'Oxygen'
    code: 'Roboto Mono'

markdown_extensions:
  - codehilite(css_class=code)
  - admonition
